---
- hosts: localhost
  become: yes

  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Add Jenkins repository key
      rpm_key:
        key: "https://pkg.jenkins.io/redhat-stable/jenkins.io.key"

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins official repository
        baseurl: "http://pkg.jenkins.io/redhat-stable"
        gpgcheck: yes

    - name: Install Jenkins
      yum:
        name: jenkins-2.346.1
        state: present

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes
